version: '3'

services:
    wordpress:
        container_name: wordpress
        image: wordpress
        environment:
            WORDPRESS_DB_USER: supinfo
            WORDPRESS_DB_PASSWORD: supinfo
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_NAME: wordpress
        ports:
         - "80:80/tcp"
        depends_on:
         - database
        deploy:
            mode: global

    vizualizer:
        container_name: vizualiser
        image: dockersamples/visualizer
        ports:
         - "8080:8080/tcp"
        volumes:
         - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                 - node.role == manager

    database:
        image: mysql:5.7
        environment:
            MYSQL_PASSWORD: supinfo
            MYSQL_DATABASE: wordpress
            MYSQL_USER: supinfo
            MYSQL_RANDOM_ROOT_PASSWORD: supinfo
        deploy:
            mode: replicated
            replicas: 1
