version: '3'

services:
    wordpress:
        container_name: wordpress
        image: wordpress
        environment:
            WORDPRESS_DB_USER: supinfo
            WORDPRESS_DB_PASSWORD: supinfo
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_NAME: wordpress
        ports:
         - "80:80/tcp"
        depends_on:
         - database
        networks:
         - app_network

    database:
        image: mysql:5.7
        environment:
            MYSQL_PASSWORD: supinfo
            MYSQL_DATABASE: wordpress
            MYSQL_USER: supinfo
            MYSQL_RANDOM_ROOT_PASSWORD: supinfo
        networks:
         - app_network

networks:
    app_network:
        ipam:
            driver: default
            config:
             - subnet: 10.0.0.0/28
